site_name: ScenTrees.jl
repo_url: https://github.com/kirui93/ScenTrees.jl
site_description: A package for generating scenario trees and scenario lattices for multistage stochastic optimization
site_author: Kipngeno Kirui
theme: readthedocs

markdown_extensions:
- codehilite
- extra
- tables
- fenced_code

extra_css:
- assets/Documenter.css

extra_javascript:
- https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS_HTML
- assets/mathjaxhelper.js

docs_dir: 'src'

pages:
- Home: index.md

